on:
  pull_request:
  push:
    branches:
      - master

name: Continuous integration

jobs:
  code_analysis:
    name: Code Analysis
    uses: dusk-network/.github/.github/workflows/code-analysis.yml@main
    with:
      clippy_default: false
      clippy_args: --release --features=rkyv/size_32,rkyv-impl,zk -- -D warnings

  dusk_analyzer:
    name: Dusk Analyzer
    uses: dusk-network/.github/.github/workflows/dusk-analysis.yml@main

  test:
    name: test core
    uses: dusk-network/.github/.github/workflows/run-tests.yml@main

  test_circuits:
    name: test zk
    uses: dusk-network/.github/.github/workflows/run-tests.yml@main
    with:
      test_flags: --features=zk
